name: Binance Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v6

      - name: Python hazırla
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Gereksinimleri kur
        run: pip install -r requirements.txt

      - name: Binance bağlantısını test et
        run: python main.py
